/*
    Program to create mastermind game.
    In this program we ask the user to guess a number generated by the program.
    If the guessed number is same as generate by the program than the player wins the game.
    Otherwise looses game if does not guess correctly within specified number of chances.
    and after both winning or loosing game the user is asked if he wants to play again or not.
*/
#include<stdio.h>
#include<stdlib.h>
#include<time.h>

/*

 Array to store elements which are repeating in the number guessed by the user , but in such a way that if that element occurs 2 times or 3 times or n times in the number guessed by the user than this array only stores that element only 1 time in it
 for example if number guessed by the user is 1277799 than elements of this array would be some zeros and 7 and 9 as only 7 and 9 are repeating
*/
int repeatingElements[10] = {0};
int x = 0; // Global variable used to mention index at which 7 and 9 in above example should be stored in the array repeatingElements[]


void checker3(int a[],int size, int value,int n); // Prototype of Function which is used to update value of variable correct_number

int arrayOfGuessedNumbers[10]; // Array to store the digits of the number guessed by the user.
int correct_number_and_location = 0; // Global Variable to store how many digits in the guessed number are correct and are at the correct location.
int correct_number = 0; //Global Variable to store how many digits in the guessed number are correct but at the wrong position as compared to the randomly generated number.

int sizeOfArray(void); // Prototype of function to ask the number of digits user wants for the randomly generated number.

int noOfAttempts(void); // Prototype of function to ask the number of attempts user wants to guess the randomly generated number.

/*
 Prototype of function which receives an array of integers, and its size.
 Then it generates random unique digits and stores them into the array.
*/
int uniqueRand(int a[], int size);

/*
 Prototype of function which receives an array of integers, size of the array, and an integer, value.
 If value is found inside the array, it returns 1, and otherwise it returns -1. This function
 will be called from the next function, uniqueRand.
 */
int found(int a[], int size, int value);


/*
Prototype of function to update the value of variable correct_number_and_location as it checks which digits in the number guessed by the user are correct and
are at the correct location as compared to the randomly generated number
*/
void checker(int a[],int size, int value,int n);


/*
    Prototype of the function which is used
    If the input entered by the user is not distinct i.e, if the number guessed by the user has some same digits
*/
void checker2(int ab[],int size,int value);

int main(void) // main function starts
{
    srand(time(NULL)); // Generate a unique value for random generator.
    int noOfGuess = 0; // Variable to count number of guesses made by the user.
    // Printing a welcome message
    puts("------------------------------");
    puts("Welcome to MasterMind Game!!!");
    puts("          Version 0               ");
    puts(" Release Date: Feb. 10, 2021");
    puts("   Programmer: Bhavya Patel.");
    puts("------------------------------");
    int playAgain = 1; // Sentinel value for outer while loop which checks that if value of  playAgain = 1 than enter the outer while loop else don't enter.
    time_t start,end; // variables to calculate time.
    double t; // Variable to store the difference ( end - start ) to get the time elapsed by the user to guess the number correctly.

    while (playAgain == 1) // while loop which is used to play the game until the value of variable playAgain becomes 0
    {
        int flg = 0; // Variable which becomes 1 if user wants to play the game again.
        int size = 0; // Variable to store the size of the randomly generated number.
        size = sizeOfArray();
        correct_number_and_location = 0;
        correct_number = 0;

        /*
             While loop to keep a check if the number of digits which user wants for randomly generated number is between (1 and 7) or not ,
             If user enters a value greater than 7 or less than 1 than it keeps asking user to enter a value between (1 - 7) ,
             and stops when user enters size between (1 - 7)
        */
        while(size<1 || size>7)
        {
            puts("Size of the number should be between 1 and 7 !!!");
            size = sizeOfArray();
        }

        int maxNoOfAttempts = 0; // Variable to store the maximum number of attempts user wants to guess the number.
        maxNoOfAttempts = noOfAttempts();

        /*
            While loop to keep a check if the maximum number of attempts user wants to guess the number is between (1 - 100) or not ,
            If user enters a value greater than 100 or less than 1 than it keeps asking user to enter a value between (1 - 100) ,
            and stops when user enters a value between (1 - 100)
        */
        while(maxNoOfAttempts<1 || maxNoOfAttempts>100)
        {
            puts("Number of attempts should be between 1 and 100 !!!");
            maxNoOfAttempts = noOfAttempts();
        }

        int z = maxNoOfAttempts; // Variable to store a copy of the value of the variable maxNoOfAttempts

        int a[size]; // Array to store digits of randomly generated number , which would be passed to function uniqueRand() by reference
        for (int i = 0;i<size;i++) // for loop to make all elements of the array , arrayOfGuessedNumbers[] equal to 0
        {
            arrayOfGuessedNumbers[i] = 0;
        }

        /*
            if condition which checks if value of variable maxNoOfAttempts is equal to z or not ,
            If maxNoOfAttempts is equal to z than only call uniqueRand() function , to generate the random number only once during 1 whole game
        */
        if (maxNoOfAttempts == z)
        {
            uniqueRand(a,size);
        }
        time(&start);
        while (maxNoOfAttempts > 0) // While loop which asks the user to guess the number until the value of variable maxNoOfAttempts is greater than 0
        {
            /*
            Variable which is used to check that if user does not enter a number whose number of digits are equal to the number
            of digits of the randomly generated number and number of attempts user has is equal to 1 , than value of f is changed to 1
            so that value of variables correct_number_and_location and correct_number are not printed as user had not entered appropriate
            number of digits and his number of attempts are also finished. As a result of which "Sorry! you lose the game." message is printed.
            */
            int f = 0;
            long long int guessNumber = 0; // variable to store the number guessed by the user.
            printf("You have %d remaining chance(s).\n",maxNoOfAttempts);
            printf("Guess a %d digit number (enter 0 to exit): \n",size);
            scanf("%lld",&guessNumber);
            int guessNumber2 = guessNumber; // Variable to store a copy of value of variable guessNumber
            int k = 0; // Variable used as a counter to count the number of digits of the number guess by the user
            if (guessNumber != 0) // if condition to check if value of variable guessNumber is not equal to 0
            {
                 while (guessNumber2>0) // while loop to update the value of variable k , to count the number of digits of the number guess by the user
                {
                    k++;
                    guessNumber2 = guessNumber2 / 10;
                }
                while (k!=size) // While loop which keeps running until user enters a number whose number of digits are equal to the value stored in the variable size
                {
                    if (maxNoOfAttempts == 1) // If value of variable maxNoOfAttempts is equal to 1 than change value of variable f to 1 and come out of the while loop
                    {
                        f = 1;
                        break;
                    }
                    printf("Please enter a %d digit number !!!\n",size);
                    maxNoOfAttempts--;
                    printf("You have %d remaining chance(s).\n",maxNoOfAttempts);
                    printf("Guess a %d digit number (enter 0 to exit): \n",size);
                    scanf("%lld",&guessNumber);
                    if (guessNumber == 0) // If user guesses the number as 0 , than we immediately exit from the while loop using break statement
                    {
                        break;
                    }
                    guessNumber2 = guessNumber;
                    k = 0;
                    while (guessNumber2>0) // while loop to update the value of variable k , to count the number of digits of the number guess by the user
                    {
                        k++;
                        guessNumber2 = guessNumber2 / 10;
                    }
                }
            }
            k = 0;
            correct_number_and_location = 0;
            correct_number = 0;
            if (guessNumber == 0) // If user guesses the number as 0 , than we ask the user if he wants to play another game or not
            {
                time(&end);

                printf("%s","Do you want to play another game?  (No:0, Yes:1)");
                scanf("%d",&playAgain);

                if (playAgain == 0) // If user does not want to play another game than immediately exit from the loop.
                {
                    break;
                }
                else if (playAgain == 1) // If user wants to play another game than exit from the current nested while loop and run the outer while loop again.
                {
                    noOfGuess = 0;
                    flg = 1;

                    break;
                }
            }
            else // else continue playing the game
            {
                noOfGuess++;
                for (int i = 0;i<size;i++) // for loop to separate each digit of the user's guessed number which is stored in variable guessNumber and then store each digit into an array named arrayOfGuessedNumbers[]
                {
                    arrayOfGuessedNumbers[i] = guessNumber % 10;
                    guessNumber = guessNumber / 10;
                }
            }
            int n = 0; // variable used to compare the index of guessed number with index of random number , to update the values of variables correct_number_and_location and correct_number
            for (int j = size -1 ;j>=0;j--) // for loop to pass the elements stored in the array , arrayOfGuessedNumbers , to function checker()
            {
                checker(a,size,arrayOfGuessedNumbers[j],n);
                n++;
            }
            for (int m = size-1;m>=0;m--) //for loop to pass the elements stored in the array , repeatingElements , to function checker2()
            {
                if (repeatingElements[m] != 0) // If the element stored in the array , repeatingElements , is not equal to 0 than pass that element to function checker2()
                {
                    checker2(arrayOfGuessedNumbers,size,repeatingElements[m]);
                }
            }
             int z = 0; // Variable to count the number of duplicate elements in the array , arrayOfGuessedNumbers
             for (int i = size-1;i>=0;i--) // loop to check each and every element of array a[] , which is the array storing the digits of the randomly generated number
            {
                int count  = 0; // Variable to count the number of times the element a[i] is present in the array , arrayOfGuessedNumbers
                for (int j = size-1;j>=0;j--) // loop to check each and every element of array arrayOfGuessedNumbers[] , which is the array storing the digits of the number guessed by the user.
                {
                    if (a[i] == arrayOfGuessedNumbers[j]) // if any digit in the randomly generated is present in the array , arrayOfGuessedNumbers[] then increment value of variable count
                    {
                        count++;
                    }
                    if (count > 1) // If value of variable count is greater than 1 than increment value of variable z by 1
                    {
                        z++;
                    }
                }
            }
            if (z!=0) // If value of variable z is not equal to 0 than enter the if condition
            {
                for (int i = size-1;i>=0;i--) // loop to check each and every element of array a[] , which is the array storing the digits of the randomly generated number
                {
                    for (int j = size-1;j>=0;j--) // loop to check each and every element of array arrayOfGuessedNumbers[] , which is the array storing the digits of the number guessed by the user.
                    {
                        if (a[i] == arrayOfGuessedNumbers[j]) // if any digit in the randomly generated is present in the array , arrayOfGuessedNumbers[] then call checker2() function and increment value of variable correct_number
                        {
                            checker2(arrayOfGuessedNumbers,size,a[i]);
                            correct_number++;
                        }
                    }
                }
            }
            int o = 0; // variable to pass it's value to checker3() function when value of global variable x is not equal to zero
            for (int j = size -1 ;j>=0;j--) // for loop to pass elements of the array , arrayOfGuessedNumbers[] to the function checker3()
            {
                if (x == 0) // If value of variable x is equal to 0 then pass variable n to the checker3() function
                {
                    checker3(a,size,arrayOfGuessedNumbers[j],n);
                }
                else if (x != 0) // If value of variable x is not equal to 0 than pass value of variable o to the checker3() function
                {
                    checker3(a,size,arrayOfGuessedNumbers[j],o);
                }

                o++;

            }
            n = 0;
            if (f!=1) // If value of variable f is not equal to 1 than only print values of variables correct_number_and_location and correct_number
            {
                printf("Correct Location & Number : %d , Correct Number : %d\n",correct_number_and_location ,correct_number);
            }

            if (correct_number_and_location == size) // If value of variable correct_number_and_location is equal to value of variable size than print the message that user has won the game and ask him if he wants to play again or not
            {
                time(&end);
                t = difftime(end,start);
                printf("Excellent!!! you solved it with %d guesses, in %2.0f seconds.\n",noOfGuess,t);
                noOfGuess = 0;
                printf("%s","Do you want to play another game?  (No:0, Yes:1)");
                scanf("%d",&playAgain);
                if (playAgain == 0) // If user does not want to play another game than immediately exit from the loop.
                {
                    break;
                }
                else if (playAgain == 1) // If user wants to play another game than go to the top to the outer while loop.
                {

                    flg = 1;
                    break;
                }
            }
             else // else continue decrementing the value of variable maxNoOfAttempts
            {
                maxNoOfAttempts--;
                if (maxNoOfAttempts ==0) // if all attempts are finished than print that the user has lost the game and ask him if he wants to play again or not
                {
                    time(&end);
                    puts("Sorry! you lose the game.");
                    noOfGuess = 0;
                    printf("%s","Do you want to play another game?  (No:0, Yes:1)");
                    scanf("%d",&playAgain);
                    if (playAgain == 0) // If user does not want to play another game than immediately exit from the loop.
                    {
                        break;
                    }
                    else if (playAgain == 1) // If user wants to play another game than go to the top to the outer while loop.
                    {

                        flg = 1;
                        break;
                    }
                }
            }
        }
        if (flg == 1) // If value of variable is equal to 1 than continue to run the outer while loop again.
        {
            continue;
        }
        else // else if value of variable is not equal to 1 than break the loop as user does not want to play another game.
        {
            break;
        }
        return 0;
    }
}

int sizeOfArray(void) // Function to ask the number of digits user wants for the randomly generated number.
{
    int size = 0; // Local variable to store the size of the randomly generated number.
    printf("Enter the size of the number between 1 and 7 : \n");
    scanf("%d",&size);
    return size;
}

int noOfAttempts(void) // Function to ask the number of attempts user wants to guess the randomly generated number.
{
    int attempts = 0; // Local variable to store the number of attempts entered by the user.
    printf("Enter number of attempts between 1 and 100 : \n");
    scanf("%d",&attempts);
    return attempts;
}

/*
 This function receives an array of integers, and its size.
 Then it generates random unique digits and stores them into the array.
*/
int uniqueRand(int a[], int size)
{
    for (int i = 0;i<size;i++) // for loop to print * to show that a random number is generated by the program.
        {
            if (i == (size-1)) // if condition which checks if value of variable i is equal to value of (size - 1) or not so that we can put a \n when we are printing last *
            {
                printf("*\n");
                continue;
            }
            printf("* ");

        }
    int randomNumber = 0; // Variable to store a single digit random number.
    int m = 0; // Variable to store the return value of function found
    for (int i = 0;i < size;i++) // for loop to store a unique single digit random number at every index of array a
    {
        while (1) // While loop which keeps generating a new single digit random number , if that single digit number is already present in the array and break if that single digit number is distinct of all other elements of the array a.
        {
            randomNumber = (rand() % 9) + 1;

            m = found(a,size,randomNumber);
            if (m == 1) // if condition to check if the value returned by the function is equal to 1 , then run the while loop again
            {
                m = 0;
                continue;
            }
            if (m == -1) // else if value returned by function found is not equal to -1 than store that single digit random number in the array and break the while loop
            {
                m = 0;
                a[i] = randomNumber;
                break;
            }
        }
    }

    return 0;
}

/*
 This function receives an array of integers, size of the array, and an integer, value.
 If value is found inside the array, it returns 1, and otherwise it returns -1. This function
 will be called from the next function, uniqueRand.
 */
int found(int a[], int size, int value)
{
    int flg[10] = {0}; // array to store 1 if value of variable value is equal to an element present in the array a[] or store -1 if value of variable value is not equal to any element present in the array a[]
    for (int i = 0;i < size;i++) // for loop to check if value stored in variable value is already present in the array a or not.
    {
        if (value == a[i]) // if condition to check if value of variable value is equal to value stored in array a at some index i, if yes then store 1 in array at index i
        {
            flg[i] = 1;
        }
        else // else store -1 in the array at index i
        {
            flg[i] = -1;
        }
    }
    for (int j = 0;j<size;j++) // for loop to go through each and every element of array containing 1 and -1
    {
        if (flg[j] == 1) // If any element of the array is equal to 1 than return 1
        {
            return 1;
        }
    }
    return -1;
}

/*
function to update the value of variable correct_number_and_location as it checks which digits in the number guessed by the user are correct and
are at the correct location as compared to the randomly generated number
*/
void checker(int a[],int size, int value,int n)
{
    for (int i = 0;i<size;i++) // for loop to check every element of array a , to compare each and element of array a with value of variable value
    {
        if (value == a[i]) // if condition to check if value of variable value is equal to any element of array a
        {
            if (n == i) // if condition to check if value of variable n is equal to i than update the value of variable correct_number_and_location and store value of variable value in the array , repeatingElements[] at index x
            {
                correct_number_and_location++;
                repeatingElements[x] = value;
                x++;
            }
        }
    }
}

/*
    function which is used if the input entered by the user is not distinct i.e, if the number guessed by the user has some same digits
*/
void checker2(int ab[],int size,int value)
{
    for (int j = size-1;j>=0;j--) // for loop to update value of variable j which is used as the index for array ab[] , to go through every element of array ab[] which is the local array of this function
    {
        if (value == ab[j]) // if value of the variable value is equal to the element of array ab[] at index j , than change the value at that index to -1
        {
            ab[j] = -1;
            continue;
        }
        else // else continue running the for loop
        {
            continue;
        }
    }
}

void checker3(int a[],int size, int value,int n) // Function used to update value of variable correct_number
{
    for (int i = 0;i<size;i++) // for loop to check if value of variable value is equal to any element in array a[] , which is local array of this function
    {
        if (value == a[i]) // If value of variable value is equal to any element of array a[] , which is local array of this function , then check if value of variable n is equal to value of variable i or not
        {
            if (n != i) // If value of variable n is not equal to value of variable i then increment the value of variable correct_number by 1
            {
                correct_number++;
            }
        }
    }
}
















